humanoid_control/armKd: 0
humanoid_control/armKi: 0
humanoid_control/armKp: 0.3
humanoid_control/arm_ctrl_flag: false
humanoid_control/ctrl_flag: false
humanoid_control/dt: 0.07
humanoid_control/kpFootPitch: 850
humanoid_control/kpFootRoll: 850
humanoid_control/kpHipPitch: 850
humanoid_control/kpHipRoll: 850
humanoid_control/kpKneePitch: 850 
humanoid_control/kpUpperBody: 850
humanoid_control/torsoKd: 0
humanoid_control/torsoKi: 0
humanoid_control/torsoKp: 0.03
humanoid_control/torso_ctrl_flag: false

